# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personinfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_change_teacherinfo(object):
    def setupUi(self, change_teacherinfo):
        change_teacherinfo.setObjectName("change_teacherinfo")
        change_teacherinfo.resize(640, 480)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        change_teacherinfo.setFont(font)
        self.label_8 = QtWidgets.QLabel(change_teacherinfo)
        self.label_8.setGeometry(QtCore.QRect(50, 90, 45, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(change_teacherinfo)
        self.label_7.setGeometry(QtCore.QRect(50, 130, 45, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(change_teacherinfo)
        self.label_6.setGeometry(QtCore.QRect(50, 170, 75, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(change_teacherinfo)
        self.lineEdit.setGeometry(QtCore.QRect(130, 90, 165, 24))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(change_teacherinfo)
        self.lineEdit_3.setGeometry(QtCore.QRect(131, 170, 161, 24))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(change_teacherinfo)
        self.pushButton.setGeometry(QtCore.QRect(370, 420, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(change_teacherinfo)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 420, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(change_teacherinfo)
        self.comboBox.setGeometry(QtCore.QRect(130, 130, 161, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(change_teacherinfo)
        self.pushButton.clicked.connect(change_teacherinfo.buttonclicked_teacher)
        self.pushButton_2.clicked.connect(change_teacherinfo.close)
        QtCore.QMetaObject.connectSlotsByName(change_teacherinfo)

    def retranslateUi(self, change_teacherinfo):
        _translate = QtCore.QCoreApplication.translate
        change_teacherinfo.setWindowTitle(_translate("change_teacherinfo", "修改信息"))
        self.label_8.setText(_translate("change_teacherinfo", "姓名："))
        self.label_7.setText(_translate("change_teacherinfo", "性别："))
        self.label_6.setText(_translate("change_teacherinfo", "联系方式："))
        self.pushButton.setText(_translate("change_teacherinfo", "确认"))
        self.pushButton_2.setText(_translate("change_teacherinfo", "返回"))
        self.comboBox.setItemText(0, _translate("change_teacherinfo", "男"))
        self.comboBox.setItemText(1, _translate("change_teacherinfo", "女"))
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personinfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_change_teacherinfo(object):
    def setupUi(self, change_teacherinfo):
        change_teacherinfo.setObjectName("change_teacherinfo")
        change_teacherinfo.resize(640, 480)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        change_teacherinfo.setFont(font)
        self.label_8 = QtWidgets.QLabel(change_teacherinfo)
        self.label_8.setGeometry(QtCore.QRect(50, 90, 45, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(change_teacherinfo)
        self.label_7.setGeometry(QtCore.QRect(50, 130, 45, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(change_teacherinfo)
        self.label_6.setGeometry(QtCore.QRect(50, 170, 75, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(change_teacherinfo)
        self.lineEdit.setGeometry(QtCore.QRect(130, 90, 165, 24))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(change_teacherinfo)
        self.lineEdit_3.setGeometry(QtCore.QRect(131, 170, 161, 24))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(change_teacherinfo)
        self.pushButton.setGeometry(QtCore.QRect(370, 420, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(change_teacherinfo)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 420, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(change_teacherinfo)
        self.comboBox.setGeometry(QtCore.QRect(130, 130, 161, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(change_teacherinfo)
        self.pushButton.clicked.connect(change_teacherinfo.buttonclicked_teacher)
        self.pushButton_2.clicked.connect(change_teacherinfo.close)
        QtCore.QMetaObject.connectSlotsByName(change_teacherinfo)

    def retranslateUi(self, change_teacherinfo):
        _translate = QtCore.QCoreApplication.translate
        change_teacherinfo.setWindowTitle(_translate("change_teacherinfo", "修改信息"))
        self.label_8.setText(_translate("change_teacherinfo", "姓名："))
        self.label_7.setText(_translate("change_teacherinfo", "性别："))
        self.label_6.setText(_translate("change_teacherinfo", "联系方式："))
        self.pushButton.setText(_translate("change_teacherinfo", "确认"))
        self.pushButton_2.setText(_translate("change_teacherinfo", "返回"))
        self.comboBox.setItemText(0, _translate("change_teacherinfo", "男"))
        self.comboBox.setItemText(1, _translate("change_teacherinfo", "女"))
