# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coursechange_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_coursechange_window(object):
    def setupUi(self, coursechange_window):
        coursechange_window.setObjectName("coursechange_window")
        coursechange_window.resize(640, 546)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        coursechange_window.setFont(font)
        self.pushButton_2 = QtWidgets.QPushButton(coursechange_window)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 500, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(coursechange_window)
        self.pushButton.setGeometry(QtCore.QRect(520, 450, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(coursechange_window)
        self.lineEdit.setGeometry(QtCore.QRect(150, 50, 200, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border:none;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(coursechange_window)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 190, 200, 41))
        self.lineEdit_3.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border:none;")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(coursechange_window)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 250, 200, 41))
        self.lineEdit_4.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border:none;")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.scrollArea = QtWidgets.QScrollArea(coursechange_window)
        self.scrollArea.setGeometry(QtCore.QRect(150, 320, 231, 191))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("border:none;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 231, 191))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.scrollAreaWidgetContents.setFont(font)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layoutWidget = QtWidgets.QWidget(coursechange_window)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 40, 91, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.comboBox = QtWidgets.QComboBox(coursechange_window)
        self.comboBox.setGeometry(QtCore.QRect(150, 130, 200, 21))
        self.comboBox.setStyleSheet("border:none;\n"
"background-color: rgb(240, 240, 240);")
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(coursechange_window)
        QtCore.QMetaObject.connectSlotsByName(coursechange_window)
        self.pushButton.clicked.connect(coursechange_window.coursecommit_button_clicked)
        self.pushButton_2.clicked.connect(coursechange_window.close)

    def retranslateUi(self, coursechange_window):
        _translate = QtCore.QCoreApplication.translate
        coursechange_window.setWindowTitle(_translate("coursechange_window", "课程详情"))
        self.pushButton_2.setText(_translate("coursechange_window", "返回"))
        self.pushButton.setText(_translate("coursechange_window", "提交"))
        self.label.setText(_translate("coursechange_window", "课程名称："))
        self.label_3.setText(_translate("coursechange_window", "所属学院："))
        self.label_4.setText(_translate("coursechange_window", "课程学时："))
        self.label_5.setText(_translate("coursechange_window", "课程容量："))
        self.label_10.setText(_translate("coursechange_window", "所需软件："))
