# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'labchange_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lab_change_window(object):
    def setupUi(self, lab_change_window):
        lab_change_window.setObjectName("lab_change_window")
        lab_change_window.resize(640, 546)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        lab_change_window.setFont(font)
        self.lineEdit = QtWidgets.QLineEdit(lab_change_window)
        self.lineEdit.setGeometry(QtCore.QRect(160, 60, 200, 47))
        self.lineEdit.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border:none;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_4 = QtWidgets.QLineEdit(lab_change_window)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 250, 200, 47))
        self.lineEdit_4.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border:none;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.scrollArea = QtWidgets.QScrollArea(lab_change_window)
        self.scrollArea.setGeometry(QtCore.QRect(160, 320, 231, 201))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("border:none;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 231, 201))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.scrollAreaWidgetContents.setFont(font)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(lab_change_window)
        self.pushButton.setGeometry(QtCore.QRect(530, 450, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(lab_change_window)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 500, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_3 = QtWidgets.QComboBox(lab_change_window)
        self.comboBox_3.setGeometry(QtCore.QRect(160, 190, 231, 47))
        self.comboBox_3.setStyleSheet("border:none;\n"
"background-color: rgb(240, 240, 240);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_2 = QtWidgets.QComboBox(lab_change_window)
        self.comboBox_2.setGeometry(QtCore.QRect(160, 130, 231, 47))
        self.comboBox_2.setStyleSheet("border:none;\n"
"background-color: rgb(240, 240, 240);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.widget = QtWidgets.QWidget(lab_change_window)
        self.widget.setGeometry(QtCore.QRect(50, 60, 107, 301))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)

        self.retranslateUi(lab_change_window)
        self.pushButton.clicked.connect(lab_change_window.labcommit_button_clicked)
        self.pushButton_2.clicked.connect(lab_change_window.close)
        QtCore.QMetaObject.connectSlotsByName(lab_change_window)

    def retranslateUi(self, lab_change_window):
        _translate = QtCore.QCoreApplication.translate
        lab_change_window.setWindowTitle(_translate("lab_change_window", "实验室详情"))
        self.pushButton.setText(_translate("lab_change_window", "提交"))
        self.pushButton_2.setText(_translate("lab_change_window", "返回"))
        self.label.setText(_translate("lab_change_window", "实验室地点："))
        self.label_2.setText(_translate("lab_change_window", "实验室管理员："))
        self.label_3.setText(_translate("lab_change_window", "实验室设备："))
        self.label_4.setText(_translate("lab_change_window", "容纳人数："))
        self.label_5.setText(_translate("lab_change_window", "拥有软件："))
