# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'labinfo_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lab_info_window(object):
    def setupUi(self, lab_info_window):
        lab_info_window.setObjectName("lab_info_window")
        lab_info_window.resize(640, 546)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        lab_info_window.setFont(font)
        self.label_6 = QtWidgets.QLabel(lab_info_window)
        self.label_6.setGeometry(QtCore.QRect(170, 60, 161, 51))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(lab_info_window)
        self.label_7.setGeometry(QtCore.QRect(170, 120, 161, 51))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(lab_info_window)
        self.label_8.setGeometry(QtCore.QRect(170, 180, 341, 51))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(lab_info_window)
        self.label_9.setGeometry(QtCore.QRect(170, 250, 161, 51))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.textBrowser = QtWidgets.QTextBrowser(lab_info_window)
        self.textBrowser.setGeometry(QtCore.QRect(160, 320, 411, 161))
        self.textBrowser.setStyleSheet("border:none;\n"
"background-color: rgb(240, 240, 240);")
        self.textBrowser.setObjectName("textBrowser")
        self.widget = QtWidgets.QWidget(lab_info_window)
        self.widget.setGeometry(QtCore.QRect(50, 60, 128, 301))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)

        self.retranslateUi(lab_info_window)
        QtCore.QMetaObject.connectSlotsByName(lab_info_window)

    def retranslateUi(self, lab_info_window):
        _translate = QtCore.QCoreApplication.translate
        lab_info_window.setWindowTitle(_translate("lab_info_window", "实验室详情"))
        self.textBrowser.setHtml(_translate("lab_info_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p></body></html>"))
        self.label.setText(_translate("lab_info_window", "实验室地点："))
        self.label_2.setText(_translate("lab_info_window", "实验室管理员："))
        self.label_3.setText(_translate("lab_info_window", "实验室设备："))
        self.label_4.setText(_translate("lab_info_window", "容纳人数："))
        self.label_5.setText(_translate("lab_info_window", "拥有软件："))
