# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logon.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_logon_window(object):
    def setupUi(self, logon_window):
        logon_window.setObjectName("logon_window")
        logon_window.resize(850, 650)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        logon_window.setFont(font)
        self.radioButton_logon = QtWidgets.QRadioButton(logon_window)
        self.radioButton_logon.setGeometry(QtCore.QRect(300, 360, 141, 31))
        self.radioButton_logon.setObjectName("radioButton_logon")
        self.lable_logon_admin = QtWidgets.QLabel(logon_window)
        self.lable_logon_admin.setGeometry(QtCore.QRect(300, 400, 131, 31))
        self.lable_logon_admin.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lable_logon_admin.setScaledContents(False)
        self.lable_logon_admin.setObjectName("lable_logon_admin")
        self.text_logon_admin = QtWidgets.QLineEdit(logon_window)
        self.text_logon_admin.setGeometry(QtCore.QRect(430, 400, 111, 26))
        self.text_logon_admin.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.text_logon_admin.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.text_logon_admin.setEchoMode(QtWidgets.QLineEdit.Password)
        self.text_logon_admin.setObjectName("text_logon_admin")
        self.button_logon_logon = QtWidgets.QPushButton(logon_window)
        self.button_logon_logon.setGeometry(QtCore.QRect(311, 490, 93, 29))
        self.button_logon_logon.setObjectName("button_logon_logon")
        self.button_logon_back = QtWidgets.QPushButton(logon_window)
        self.button_logon_back.setGeometry(QtCore.QRect(434, 490, 93, 29))
        self.button_logon_back.setObjectName("button_logon_back")
        self.widget = QtWidgets.QWidget(logon_window)
        self.widget.setGeometry(QtCore.QRect(302, 243, 240, 94))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lable_logon_user = QtWidgets.QLabel(self.widget)
        self.lable_logon_user.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lable_logon_user.setObjectName("lable_logon_user")
        self.gridLayout.addWidget(self.lable_logon_user, 0, 0, 1, 1)
        self.text_logon_user = QtWidgets.QLineEdit(self.widget)
        self.text_logon_user.setObjectName("text_logon_user")
        self.gridLayout.addWidget(self.text_logon_user, 0, 1, 1, 1)
        self.label_logon_pass = QtWidgets.QLabel(self.widget)
        self.label_logon_pass.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_logon_pass.setObjectName("label_logon_pass")
        self.gridLayout.addWidget(self.label_logon_pass, 1, 0, 1, 1)
        self.text_logon_pass = QtWidgets.QLineEdit(self.widget)
        self.text_logon_pass.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.text_logon_pass.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.text_logon_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.text_logon_pass.setObjectName("text_logon_pass")
        self.gridLayout.addWidget(self.text_logon_pass, 1, 1, 1, 1)
        self.lable_logon_pass2 = QtWidgets.QLabel(self.widget)
        self.lable_logon_pass2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lable_logon_pass2.setObjectName("lable_logon_pass2")
        self.gridLayout.addWidget(self.lable_logon_pass2, 2, 0, 1, 1)
        self.text_logon_pass2 = QtWidgets.QLineEdit(self.widget)
        self.text_logon_pass2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.text_logon_pass2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.text_logon_pass2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.text_logon_pass2.setObjectName("text_logon_pass2")
        self.gridLayout.addWidget(self.text_logon_pass2, 2, 1, 1, 1)

        self.retranslateUi(logon_window)
        self.button_logon_logon.clicked.connect(logon_window.logon)
        self.button_logon_back.clicked.connect(logon_window.back)
        QtCore.QMetaObject.connectSlotsByName(logon_window)

    def retranslateUi(self, logon_window):
        _translate = QtCore.QCoreApplication.translate
        logon_window.setWindowTitle(_translate("logon_window", "注册界面"))
        self.radioButton_logon.setText(_translate("logon_window", "是否注册为管理员"))
        self.lable_logon_admin.setText(_translate("logon_window", "请输入管理员口令"))
        self.button_logon_logon.setText(_translate("logon_window", "注册"))
        self.button_logon_back.setText(_translate("logon_window", "返回"))
        self.lable_logon_user.setText(_translate("logon_window", "用户名"))
        self.label_logon_pass.setText(_translate("logon_window", "密码"))
        self.lable_logon_pass2.setText(_translate("logon_window", "再次输入"))
