# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\softwareinfo_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_softwareinfo(object):
    def setupUi(self, softwareinfo):
        softwareinfo.setObjectName("softwareinfo")
        softwareinfo.resize(640, 480)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        softwareinfo.setFont(font)
        self.textBrowser = QtWidgets.QTextBrowser(softwareinfo)
        self.textBrowser.setGeometry(QtCore.QRect(150, 320, 411, 91))
        self.textBrowser.setStyleSheet("border:none;\n"
"background-color: rgb(240, 240, 240);")
        self.textBrowser.setObjectName("textBrowser")
        self.label_software_name = QtWidgets.QLabel(softwareinfo)
        self.label_software_name.setGeometry(QtCore.QRect(150, 50, 211, 47))
        self.label_software_name.setText("")
        self.label_software_name.setObjectName("label_software_name")
        self.label_software_version = QtWidgets.QLabel(softwareinfo)
        self.label_software_version.setGeometry(QtCore.QRect(150, 103, 201, 48))
        self.label_software_version.setText("")
        self.label_software_version.setObjectName("label_software_version")
        self.label_software_type = QtWidgets.QLabel(softwareinfo)
        self.label_software_type.setGeometry(QtCore.QRect(150, 157, 221, 47))
        self.label_software_type.setText("")
        self.label_software_type.setObjectName("label_software_type")
        self.label_software_arch = QtWidgets.QLabel(softwareinfo)
        self.label_software_arch.setGeometry(QtCore.QRect(150, 210, 221, 48))
        self.label_software_arch.setText("")
        self.label_software_arch.setObjectName("label_software_arch")
        self.label_software_memery = QtWidgets.QLabel(softwareinfo)
        self.label_software_memery.setGeometry(QtCore.QRect(150, 264, 241, 47))
        self.label_software_memery.setText("")
        self.label_software_memery.setObjectName("label_software_memery")
        self.splitter = QtWidgets.QSplitter(softwareinfo)
        self.splitter.setGeometry(QtCore.QRect(50, 50, 91, 311))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.splitter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.splitter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.splitter)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(softwareinfo)
        QtCore.QMetaObject.connectSlotsByName(softwareinfo)

    def retranslateUi(self, softwareinfo):
        _translate = QtCore.QCoreApplication.translate
        softwareinfo.setWindowTitle(_translate("softwareinfo", "软件详情"))
        self.textBrowser.setHtml(_translate("softwareinfo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("softwareinfo", "软件名称："))
        self.label_2.setText(_translate("softwareinfo", "软件版本："))
        self.label_3.setText(_translate("softwareinfo", "软件类型："))
        self.label_4.setText(_translate("softwareinfo", "软件架构："))
        self.label_5.setText(_translate("softwareinfo", "占用空间："))
        self.label_6.setText(_translate("softwareinfo", "软件描述："))
