# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\softwarechange_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_softwarechange(object):
    def setupUi(self, softwarechange):
        softwarechange.setObjectName("softwarechange")
        softwarechange.resize(640, 480)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        softwarechange.setFont(font)
        self.pushButton = QtWidgets.QPushButton(softwarechange)
        self.pushButton.setGeometry(QtCore.QRect(380, 430, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(softwarechange)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 430, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(softwarechange)
        self.lineEdit.setGeometry(QtCore.QRect(150, 50, 200, 47))
        self.lineEdit.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border:none;")
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(softwarechange)
        self.textEdit.setGeometry(QtCore.QRect(150, 320, 391, 101))
        self.textEdit.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border:none;")
        self.textEdit.setObjectName("textEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(softwarechange)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 100, 200, 47))
        self.lineEdit_2.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border:none;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(softwarechange)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 150, 200, 47))
        self.lineEdit_3.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border:none;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(softwarechange)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 210, 200, 47))
        self.lineEdit_4.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border:none;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(softwarechange)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 260, 200, 47))
        self.lineEdit_5.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border:none;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.widget = QtWidgets.QWidget(softwarechange)
        self.widget.setGeometry(QtCore.QRect(51, 51, 77, 301))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)

        self.retranslateUi(softwarechange)
        self.pushButton.clicked.connect(softwarechange.softcommit_button_clicked)
        self.pushButton_2.clicked.connect(softwarechange.close)
        QtCore.QMetaObject.connectSlotsByName(softwarechange)

    def retranslateUi(self, softwarechange):
        _translate = QtCore.QCoreApplication.translate
        softwarechange.setWindowTitle(_translate("softwarechange", "软件详情"))
        self.pushButton.setText(_translate("softwarechange", "提交"))
        self.pushButton_2.setText(_translate("softwarechange", "返回"))
        self.label.setText(_translate("softwarechange", "软件名称："))
        self.label_2.setText(_translate("softwarechange", "软件版本："))
        self.label_3.setText(_translate("softwarechange", "软件类型："))
        self.label_4.setText(_translate("softwarechange", "软件架构："))
        self.label_5.setText(_translate("softwarechange", "占用空间："))
        self.label_6.setText(_translate("softwarechange", "软件描述："))
