# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userinfo_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_userinfo_window(object):
    def setupUi(self, userinfo_window):
        userinfo_window.setObjectName("userinfo_window")
        userinfo_window.resize(850, 650)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        userinfo_window.setFont(font)
        self.tableWidget = QtWidgets.QTableWidget(userinfo_window)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 850, 650))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)

        self.retranslateUi(userinfo_window)
        QtCore.QMetaObject.connectSlotsByName(userinfo_window)

    def retranslateUi(self, userinfo_window):
        _translate = QtCore.QCoreApplication.translate
        userinfo_window.setWindowTitle(_translate("userinfo_window", "用户详情"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("userinfo_window", "用户编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("userinfo_window", "用户类型"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("userinfo_window", "用户姓名"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("userinfo_window", "用户账号"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("userinfo_window", "用户密码"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("userinfo_window", "用户状态"))
